theme: jekyll-theme-slate
title: Fernando Alarid-Escudero
tagline: It's all about the consequences
description: It's all about the consequences
markdown: kramdown
layout: sidebar
author :
  name : Fernando Alarid-Escudero
  email : fernando.alarid@cide.edu
  github : feralaes
  twitter : feralaes
  
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name
